<?php
namespace Rila;

/**
 * Handles the grouping of content blocks and their display.
 *
 * @since 0.1
 */
class Builder implements \Iterator, \Countable {
	/**
	 * Generates the needed layout groups for an ACF flexible content field.
	 *
	 * @since 0.1
	 *
	 * @param string[] $blocks The enabled content blocks.
	 * @return mixed[] The array for the 'layouts' option of an ACF field.
	 */
	public static function generate( $blocks ) {
		return array_map( array( Block::class, 'get_hash' ), $blocks );
	}

	/**
	 * Sets up a repeater for Ultimate Fields.
	 *
	 * @since 0.3
	 *
	 * @param UF3\Field\Repeater $field  A repeater field to setup.
	 * @param string[]           $blocks The blocks to use.
	 */
	public static function setup_repeater( $field, $blocks ) {
		foreach( $blocks as $block ) {
			$field->add_group( call_user_func( array( Block::class, 'get_group' ), $block ) );
		}

		return $field;
	}

	/**
	 * Holds raw data, which contains block, but is used only
	 * for the initialisation of the block.
	 *
	 * @since 0.1
	 * @var mixed
	 */
	protected $data = array();

	/**
	 * Holds the blocks of the builder.
	 *
	 * @since 0.1
	 * @var mixed[]
	 */
	protected $blocks = array();

	/**
	 * Holds the index of the current block.
	 *
	 * @since 0.1
	 * @var int
	 */
	protected $pointer = 0;

	/**
	 * Initializes the class by receiving an array of content blocks.
	 *
	 * !! This class can be directly mapped within an item. !!
	 *
	 * @since 0.1
	 *
	 * @param mixed[] $blocks The existing blocks.
	 */
	public function __construct( $data ) {
		if( ! $data || ! is_array( $data ) ) {
			return;
		}

		$this->data = $data;
	}

	/**
	 * Turns blocks into actual content blocks.
	 *
	 * @since 0.1
	 */
	protected function init() {
		if( ! empty( $this->blocks ) || empty( $this->data ) ) {
			return;
		}

		$index = 0;
		foreach( $this->data as $block ) {
			if( ! isset( $block[ '__type' ] ) )
				continue;

			$block['__index'] = $index++;
			$type = $block[ '__type' ];
			$type = str_replace( '_ns_', '\\', $type );

			if( ! class_exists( $type ) ) {
				continue;
			}

			$this->blocks = array_merge( $this->blocks, $type::factory( $block ) );
		}
	}


	/**
	 * Returns the currently selected block.
	 *
	 * @since 0.1
	 * @return mixed
	 */
	public function current() {
		$this->init();

		return $this->blocks[ $this->pointer ];
	}

	/**
	 * Returns the current key.
	 *
	 * @since 0.1
	 * @return scalar
	 */
	public function key() {
		$this->init();

		return $this->pointer;
	}

	/**
	 * Goes to the next item.
	 *
	 * @since 0.1
	 * @return void
	 */
	public function next() {
		$this->pointer++;
	}

	/**
	 * Rewinds the loop.
	 *
	 * @since 0.1
	 * @return void
	 */
	public function rewind() {
		$this->pointer = 0;
	}

	/**
	 * Checks if there is an element at the current index.
	 *
	 * @since 0.1
	 * @return boolean
	 */
	public function valid() {
		$this->init();

		return $this->pointer < count( $this->blocks );
	}

	/**
	 * Returns the amount of elements in the collection.
	 *
	 * @since 0.1
	 *
	 * @return int
	 */
	public function count() {
		$this->init();

		return count( $this->blocks );
	}

	/**
	 * Renders the builder and it's blocks.
	 *
	 * @since 0.1
	 *
	 * @return string The full HTML of the builder and its blocks.
	 */
	public function render() {
		$this->init();
		$out     = '';
		$of_type = array();

		foreach( $this->blocks as $index => $block ) {
			$simplified = rila_cleanup_class( get_class( $block ), 'Block' );
			$simplified = strtolower( $simplified );

			# Remove misc. characters
			$simplified = preg_replace( '~[_\\\\\s]~', '-', $simplified );

			# Generate the appropriate index for the type
			if( isset( $of_type[ $simplified ] ) ) {
				$type_index = ++$of_type[ $simplified ];
			} else {
				$type_index = $of_type[ $simplified ] = 0;
			}

			if( method_exists( $block, 'get_css_class' ) ) {
				/**
				 * Allows the CSS class of the block to be generated by the block itself.
				 *
				 * @since 0.11
				 *
				 * @param  int $index      The index of the block (starting with 0).
				 * @param  int $type_index The index of the specific blocks' type.
				 * @return string          A full CSS class.
				 */
				$css_class = $block->get_css_class( $index, $of_type[ $simplified ] );
 			} else {
				$classes = array(
					'block',
					'block-' . $simplified,
					'block-' . ( $index + 1 )
				);

				$css_class = implode( ' ', $classes );
			}

			/**
			 * Allows the CSS class of a block to be modified.
			 *
			 * @since 0.11
			 *
			 * @param string     $css_class The already-generated CSS class.
			 * @param Rila\Block $block The block whose class is being generated.
			 * @param int        $index The zero-based index of the block.
			 * @param int        $of_type The zero-based occurence of the blocks' type.
			 * @return string
			 */
			$css_class = apply_filters( 'rila.builder.block_class', $css_class, $block, $index, $of_type[ $simplified ] );

			/**
			* Allows the opening element for a block to be modified.
			*
			* @since 0.1
			*
			* @param string $html  The opening HTML.
			* @param Block  $block The block and it's data.
			* @return string
			*/
			$before = apply_filters( 'rila.builder.before_block', '<div class="' . $css_class . '">', $block );

			/**
			* Allows the closing element for a block to be modified.
			*
			* @since 0.1
			*
			* @param string $html  The closing HTML.
			* @param Block  $block The block and it's data.
			* @return string
			*/
			$after = apply_filters( 'rila.builder.after_block', '</div>', $block );

			$out .= $before . $block->toString() . $after;
		}

		return $out;
	}

	/**
	 * Converts the whole builder to a string by rendering it's content.
	 *
	 * @since 0.1
	 * @return string
	 */
	public function __toString() {
		return rila_convert_to_string( $this, 'render' );
	}
}
